/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.twostack.gradle

import org.gradle.internal.os.OperatingSystem
import java.io.File
import org.gradle.testkit.runner.GradleRunner
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * A simple functional test for the 'org.twostack.gradle.scrypt.greeting' plugin.
 */
class ScryptGradlePluginFunctionalTest {
    @Test
    fun `can run task`() {
        // Setup the test build
        val projectDir = File("build/functionalTest")
        val userHome = System.getProperty("user.home")
        projectDir.resolve("settings.gradle").writeText("")
        projectDir.resolve("build.gradle").writeText("""
            plugins {
                id('org.twostack.gradle.scrypt')
                
            }
            
            scrypt {
                compilerHome = "${userHome}/.vscode/extensions/bsv-scrypt.scrypt-1.1.0/"
            }
        """)

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments("compile")
        runner.withProjectDir(projectDir)
        val result = runner.build();

        // Verify the result
        assertTrue(result.output.contains("Version"))
    }

}
